### ISSUE TITLE
InputSTR

### ISSUE THREAD

**Issue by bbldn** [Dronii/PasPars#1]
А почему не сделать ввод элементов циклом?
Тогда метод InputSTR будет выглядеть вот так:

```c#
public static void InputSTR(string[] vs)
{
    Console.WriteLine("Сколько элементов будет в пароле? \n Введите число от 2 до 6");
    string selectionString = Console.ReadLine();
    int selection = Int32.Parse(selectionString);
    string[] arr = new string[selection];

    for (int i = 0; i < selection; i++) {
        Console.WriteLine(string.Format("Введите {0} элемент", i));
        arr[i] = Console.ReadLine();
        Console.WriteLine();
    }

    ShowAllCmbinations(arr);
}
```

**Comment by Dronii** [comment]
Int32.Parse(selectionString); <= Это преобразование в int. Если там Char например, то будет ошибка

**Comment by bbldn** [comment]
> Int32.Parse(selectionString); <= Это преобразование в int. Если там Char например, то будет ошибка

Я знаю, надо в try catch брать, тут я не стал этого делать, для простоты понимания моей мысли

**Comment by Dronii** [comment]
Ну может как-нибудь переделаю. Но сейчас я перешел к другой теме и пока не хочу заморачиваться

**Comment by Dronii** [comment]
Вообще пока не окончательный вариант))

**Comment by bbldn** [comment]
> Вообще пока не окончательный вариант))

Та ещё по коментам есть вопрос. И по алгоритму реализация. По коментам, потом обсудим если будем гулять, а вот за алгоритм, я другой issue создам

**Comment by bbldn** [comment]
https://github.com/Dronii/PasPars/issues/2
