### ISSUE TITLE
Рекурсия

### ISSUE THREAD

**Issue by bbldn** [Dronii/PasPars#2]
В целом ничего плохого в рекурсии нет. Но если есть возможность ею не пользоваться, то лучше ей не пользоваться. (ИМХО). По этому предлагаю вариант реализации твоей функции перебора без рекурсии:

```C#
public static int Factorial(int number)
{
    if (number < 2) 
    {
        return number;
    }

    int total = 1;
    for (int i = 2; i <= number; i++) 
    {
        total *= i;
    }
	
    return total;
}
        
public static void ShowAllCmbinations<T>(IList<T> arr)
{    
     List<T> clone = new List<T>(arr);
            
     int numberOfArr = arr.Count;
     int numberOfSteps = Factorial(numberOfArr);
     for (int step = 0, index = 1; step < numberOfSteps; step++, index++) 
     {
         if (index >= numberOfArr) 
         {
             index = 1;
         }

         tmpIndex = index - 1;

         T tmp = clone[tmpIndex];
         clone[tmpIndex] = clone[index];
         clone[index] = tmp;
         for (int j = 0; j < clone.Count; j++) 
         {
             Console.Write(clone[j]);
         }
 
         Console.WriteLine();
    }
}
```

**Comment by Dronii** [comment]
ТАки что плохого в рекурсии?))

**Comment by bbldn** [comment]
> ТАки что плохого в рекурсии?))
> 

Я не знаю оптимизирует ли виртуалка C# рекурсию (точно не уверен), но в Си она занимает больше памяти, и работает медленнее. Это происходит из-за того, что под капотом у функции есть пролог и эпилог и по этому приходится при каждом вызове их выполнять. 
Почитай про пролог и эпилог в функциях в ассемблере.

**Comment by bbldn** [comment]
http://datadump.ru/function-prologue-epilogue
Вот норм статья
